### ISSUE TITLE
[Refactor]  Reorganize main branch structure and improve code readability

### ISSUE THREAD

**Issue by 2JAE22** [boostcampaitech7/level1-imageclassification-cv-02#10]
## 🔍 Background
- main branch의 파일 구조가 복잡하고 비효율적으로 관리되고 있음
- csv, py 등의 파일들이 root 디렉토리에 산재해 있어 프로젝트 구조 파악이 어려움
- config 폴더의 내용이 현재 팀 상황과 맞지 않아 수정이 필요
- 전반적인 폴더 구조가 baseline_code에 비해 복잡하여 간소화가 필요함.
- 불필요한 숨김 파일들이 존재하여 정리가 필요한 상황

## ✅ TO-DO
- [x]  **파일재배치** :
-  csv, py 파일 다른 폴더로 옮기기 및 결과물도 따로 다른 폴더로 만들기.
- ex) data 폴더에 csv파일을, 'src'폴더에 py 파일들을 배치
- 결과물을 저장할 "output" 또는 "results" 폴더를 새로 생성.

- [x]  **설정파일수정**: config 에 있는 우리 팀이랑 맞지 않는 내용들 고치기(ex_ config 파일에 적혀져 있는 박성현멘토님의 경로 또는 Mnist 불러오는 것등)
- [x] **폴더구조개선**:
- baseline code에 있는것 처럼  폴더를 최대한 간소화. 
- 유사한 기능의 파일들을 논리적으로 그룹화하여 새 폴더에 배치
- 폴더 이름을 직관적이고 간결하게 변경(ex_ data_processing, models, 등)
- 불필요하거나 사용하지 않는 폴더나 파일은 과감하게 삭제.

- [x] **숨겨진 파일 정리**:
-  .__ <- 이렇게 되어 있는 것들은 맥에서 생긴 캐싱 또는 숨겨진 파일(.DS_store)이라서 지워도 괜찮음(기능상 아무런 문제 없음) 
- 다만, `.gitignore`, `.dvcignore` 같이 프로젝트에 필요한 숨김파일은 있어야 함.
- [x] **코드최적화** : 팀에 맞지 않는 코드나 폴더라고 생각되면 Issue 로 만들어서 PR 하깅
