### ISSUE TITLE
[refactor] reorganize (2) 

### ISSUE THREAD

**Issue by 2JAE22** [boostcampaitech7/level1-imageclassification-cv-02#13]
## 🔍 Issue Description
-  파일 및 폴더의 이름이 겹치고 있고(data폴더) ,README.md 의 수정이 필요, 또한 requirements.txt 의 패키지 목록이 의존성 패키지까지 나와있어서 보기 힘들어서 수정.

## ✅ TO-DO
- [ ]  data(csv있는 폴더) 이름 -> dataset 으로 수정
- [ ]  README.md  수정( 필요없는 캐싱파일 및 datafile 삭제 커맨드 추가. )
- [ ]  requirements.txt 의존성 빼고 적기.
