### ISSUE TITLE
[feat] Data Augmentation + preprocessing 구현

### ISSUE THREAD

**Issue by kim-minsol** [boostcampaitech7/level1-imageclassification-cv-02#14]
## 🔍 Issue Description
데이터 흑백이미지 처리 및 증강 구현하기

코드 위치: src/data/custom_datamodules/sketch_datamodule.py
augmentation config 위치: configs/augmentation_configs/sketch_augmentation.yaml

## ✅ TO-DO
- [ ] transfrom에 grayscale 변환하는 코드 추가
- [ ] normalize에 [데이터셋에 맞는 평균/표준편차] 값 적용하기
- [ ] 밝기 + 채도 변환하는 augmentation 적용해보기
- [ ] 색 반전 augmentation 적용해보기 (!)
- [ ] 문제의 폴더(n02113712) 30장 정도 날려서 학습해보기
