### ISSUE TITLE
[feat] CNN 모델 ResNet Test

### ISSUE THREAD

**Issue by Gwonee** [boostcampaitech7/level1-imageclassification-cv-02#20]
## 🔍 Issue Description
ResNet 중 3가지 ResNet34, ResNet50, ResNet101에 대한 테스트

## ✅ TO-DO
- [x] ResNet34 params, batch_size, scheduler 조정 및 학습
- [x] ResNet50 params, batch_size, scheduler 조정 및 학습
- [x] ResNet101 params, batch_size, scheduler 조정 및 학습
