### ISSUE TITLE
[feat] Ensemble 구현하기

### ISSUE THREAD

**Issue by joonhyunkim1** [boostcampaitech7/level1-imageclassification-cv-02#36]
## 🔍 Issue Description
Eva 모델과 Convnext 모델의 Ensemble 구현

## ✅ TO-DO
- [ ] ensemble_config.yaml 파일 작성
- [ ] 두 모델의 checkpoint 확인
- [ ] Ensemble 된 모델의 train 및 test 결과 확인
