### ISSUE TITLE
[feat] test.py 구현 + model weights freezing

### ISSUE THREAD

**Issue by kim-minsol** [boostcampaitech7/level1-imageclassification-cv-02#4]
## 🔍 Issue Description
test.py 파일로 csv 파일 출력하는 코드랑 model weights freezing하는 코드 작성했어요..!
(미리 만들어버려서 커밋 합쳐져버렸어요ㅠㅠㅠ 쏘리,,,)

## ✅ TO-DO
- [ ] test.py 구현
- [ ] test의 config 파일 수정하기
- [ ] csv 파일로 저장하기
- [ ] timm_model.py에서 model weights freezing 부분 추가
